#!/usr/bin/env bash

# Workspaces
bspc monitor -d α β γ δ ε

# Window appearance
bspc config border_width         2
bspc config window_gap           60
bspc config focused_border_color "#ffffff"
bspc config normal_border_color  "#444444"

# Layout
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Mouse
bspc config focus_follows_pointer true

# Rules
bspc rule -a Emacs state=tiled

# Startup applications

# Start sxhkd for keybindings
pgrep -x sxhkd > /dev/null || sxhkd &

# Set the wallpaper
feh --no-fehbg --bg-fill ~/.eudoxia.d/data/wallpaper/panther.jpg &

# Better default pointer style
xsetroot -cursor_name left_ptr &

# Start polybar
polybar &

# These services are killed by exiting the window manager. Ensure they are
# running on startup.
systemctl --user start xscreensaver &
systemctl --user start network-manager-applet &
systemctl --user start xcape &
systemctl --user start xdg-desktop-portal-gtk &
