#!/usr/bin/env bash

# Workspaces
bspc monitor -d α β γ δ ε

# Window appearance
bspc config border_width         2
bspc config window_gap          30
bspc config focused_border_color "#ffffff"
bspc config normal_border_color  "#444444"

# Layout
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Mouse
bspc config focus_follows_pointer true

# Rules
bspc rule -a Emacs state=tiled

# Startup applications

# Start sxhkd for keybindings
pgrep -x sxhkd > /dev/null || sxhkd &

# Set the wallpaper
feh --no-fehbg --bg-fill ~/.eudoxia.d/data/wallpaper/semiramis.jpg &

# Better default pointer style
xsetroot -cursor_name left_ptr

# Start polybar
killall -q polybar
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
polybar 2> ~/.polybar.log &

# Ensure xscreensaver is started
systemctl --user start xscreensaver

# Restart services that are killed by quitting the window manager
systemctl --user start nm-applet
systemctl --user start xcape
systemctl --user start xdg-desktop-portal-gtk

# Host-specific config
HOSTNAME=$(hostname)
if [ "$HOSTNAME" = "rostam" ]; then
    export GDK_DPI_SCALE=1.5
    export QT_SCALE_FACTOR=1.5
fi
