# -*- Mode: ruby -*-

HDIR = "../code"
GDIR = "/home/vagrant/code"

ROOT = "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_"
SUFFIX = "_chef-provisionerless.box"

def url(box_name)
  return ROOT + box_name + SUFFIX
end

Vagrant.configure("2") do |config|
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
  end

  config.vm.define "ubuntu" do |m|
    m.vm.box = "ubuntu-14.04"
    m.vm.box_url = url(m.vm.box)

    m.vm.synced_folder HDIR, GDIR
  end

  config.vm.define "debian" do |m|
    m.vm.box = "debian-7.4"
    m.vm.box_url = url(m.vm.box)

    m.vm.synced_folder HDIR, GDIR
  end

  config.vm.define "centos" do |m|
    m.vm.box = "centos-6.5"
    m.vm.box_url = url(m.vm.box)

    m.vm.synced_folder HDIR, GDIR
  end

  config.vm.define "freebsd" do |m|
    m.vm.box = "freebsd-10.0"
    m.vm.box_url = url(m.vm.box)
    m.vm.guest = :freebsd

    m.vm.synced_folder HDIR, GDIR, :nfs => true

    config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--ioapic", "on"]
      vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
      vb.customize ["modifyvm", :id, "--usb", "off"]
      vb.customize ["modifyvm", :id, "--usbehci", "off"]
      vb.customize ["modifyvm", :id, "--audio", "none"]
      vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
      vb.customize ["modifyvm", :id, "--nictype2", "virtio"]
    end
  end
end
