after-startup-command = []
start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 30
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
automatically-unhide-macos-hidden-apps = true

[key-mapping]
    preset = 'qwerty'

# Gaps between windows (inner-*) and between monitor edges (outer-*).
[gaps]
    inner.horizontal = 25
    inner.vertical =   25

    outer.left =       25
    outer.bottom =     25
    outer.top =        25
    outer.right =      25

[mode.main.binding]
    alt-slash = 'layout tiles horizontal vertical'
    alt-comma = 'layout accordion horizontal vertical'
    alt-c = '''exec-and-forget osascript -e '
        tell application "Ghostty"
            activate
        end tell'
    '''
    alt-h = 'focus left'
    alt-j = 'focus down'
    alt-k = 'focus up'
    alt-l = 'focus right'

    alt-shift-h = 'move left'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move right'

    alt-minus = 'resize smart -50'
    alt-equal = 'resize smart +50'

    alt-1 = 'workspace todo'
    alt-2 = 'workspace www'
    alt-3 = 'workspace term'
    alt-4 = 'workspace edit'

    alt-shift-1 = 'move-node-to-workspace todo'
    alt-shift-2 = 'move-node-to-workspace www'
    alt-shift-3 = 'move-node-to-workspace term'
    alt-shift-4 = 'move-node-to-workspace edit'
