after-startup-command = []
start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 30
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
automatically-unhide-macos-hidden-apps = true

[key-mapping]
    preset = 'qwerty'

[gaps]
    inner.horizontal = 100
    inner.vertical =   100

    outer.left =       100
    outer.bottom =     100
    outer.top =        100
    outer.right =      100

[mode.main.binding]
    cmd-ctrl-slash = 'layout tiles horizontal vertical'
    cmd-ctrl-comma = 'layout accordion horizontal vertical'

    cmd-ctrl-minus = 'resize smart -50'
    cmd-ctrl-equal = 'resize smart +50'

    alt-1 = 'workspace todo'
    alt-2 = 'workspace www'
    alt-3 = 'workspace term'
    alt-4 = 'workspace edit'

    alt-shift-1 = 'move-node-to-workspace todo'
    alt-shift-2 = 'move-node-to-workspace www'
    alt-shift-3 = 'move-node-to-workspace term'
    alt-shift-4 = 'move-node-to-workspace edit'

    cmd-ctrl-r = 'reload-config'

    cmd-ctrl-c = 'exec-and-forget open -a Calendar'
    cmd-ctrl-e = 'exec-and-forget open -a Zed'
    cmd-ctrl-f = 'exec-and-forget open -a Finder'
    cmd-ctrl-g = 'exec-and-forget open -a Ghostty'
    cmd-ctrl-o = 'exec-and-forget open -a Obsidian'
    cmd-ctrl-t = 'exec-and-forget open -a Todoist'
    cmd-ctrl-w = 'exec-and-forget open -a Firefox'
