matches:
  - trigger: ":espanso"
    replace: "Hi there!"

  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

  # Emojis
  - { trigger: ":admin", replace: "📝" }
  - { trigger: ":alarm", replace: "⏰" }
  - { trigger: ":art", replace: "🎨" }
  - { trigger: ":ask", replace: "💬" }
  - { trigger: ":basket", replace: "🧺" }
  - { trigger: ":battery", replace: "🔋" }
  - { trigger: ":bed", replace: "🛏️" }
  - { trigger: ":bento", replace: "🍱" }
  - { trigger: ":bird", replace: "🐦" }
  - { trigger: ":block", replace: "💹" }
  - { trigger: ":blush", replace: "😊" }
  - { trigger: ":books", replace: "📚" }
  - { trigger: ":box", replace: "📦" }
  - { trigger: ":brush", replace: "🪥" }
  - { trigger: ":cal", replace: "📆" }
  - { trigger: ":cart", replace: "🛒" }
  - { trigger: ":charge", replace: "🔋" }
  - { trigger: ":chore", replace: "🔧" }
  - { trigger: ":coffee", replace: "☕" }
  - { trigger: ":cook", replace: "🍳" }
  - { trigger: ":dash", replace: "💨" }
  - { trigger: ":disc", replace: "💿" }
  - { trigger: ":down", replace: "⬇️" }
  - { trigger: ":drop", replace: "💧" }
  - { trigger: ":dry", replace: "💨" }
  - { trigger: ":env", replace: "✉️" }
  - { trigger: ":feat", replace: "🌿" }
  - { trigger: ":fence", replace: "🚧" }
  - { trigger: ":film", replace: "🎬" }
  - { trigger: ":folder", replace: "📁" }
  - { trigger: ":heart", replace: "❤️" }
  - { trigger: ":iron", replace: "♨️" }
  - { trigger: ":laptop", replace: "💻" }
  - { trigger: ":log", replace: "📝" }
  - { trigger: ":mag", replace: "🔍" }
  - { trigger: ":milk", replace: "🥛" }
  - { trigger: ":muscle", replace: "💪" }
  - { trigger: ":phone", replace: "☎️" }
  - { trigger: ":pill", replace: "💊" }
  - { trigger: ":razor", replace: "🪒" }
  - { trigger: ":read", replace: "📖" }
  - { trigger: ":shake", replace: "🥛" }
  - { trigger: ":shave", replace: "🪒" }
  - { trigger: ":shirt", replace: "👕" }
  - { trigger: ":shop", replace: "🛍️" }
  - { trigger: ":shower", replace: "🚿" }
  - { trigger: ":sleep", replace: "😪" }
  - { trigger: ":soap", replace: "🧼" }
  - { trigger: ":steam", replace: "♨️" }
  - { trigger: ":tag", replace: "🔖" }
  - { trigger: ":talk", replace: "💬" }
  - { trigger: ":tea", replace: "🍵" }
  - { trigger: ":tooth", replace: "🦷" }
  - { trigger: ":tp", replace: "🧻" }
  - { trigger: ":train", replace: "🚄" }
  - { trigger: ":tram", replace: "🚊" }
  - { trigger: ":trash", replace: "🗑️" }
  - { trigger: ":wait", replace: "⏳" }
  - { trigger: ":walk", replace: "🚶‍♂️" }
  - { trigger: ":wash", replace: "💦" }
  - { trigger: ":water", replace: "💧" }
  - { trigger: ":wolf", replace: "🐺" }
  - { trigger: ":write", replace: "✍️" }
  - { trigger: ":zzz", replace: "💤" }
