# -*- mode: i3wm-config -*-

# $mod is the Windows key.
set $mod Mod4

output eDP-1 mode 2880x1800@90Hz scale 2.0 bg /home/eudoxia/.eudoxia.d/data/wallpaper/panther.jpg fill

gaps inner 25
gaps outer 10

bindsym $mod+1 workspace "α"
bindsym $mod+2 workspace "β"
bindsym $mod+3 workspace "γ"
bindsym $mod+4 workspace "δ"
bindsym $mod+5 workspace "ε"
bindsym $mod+Control+c exec foot
bindsym $mod+Control+e exec emacs
bindsym $mod+Control+f exec thunar
bindsym $mod+Control+w exec firefox
bindsym $mod+Shift+1 move container to workspace "α"
bindsym $mod+Shift+2 move container to workspace "β"
bindsym $mod+Shift+3 move container to workspace "γ"
bindsym $mod+Shift+4 move container to workspace "δ"
bindsym $mod+Shift+5 move container to workspace "ε"
bindsym $mod+Shift+b scratchpad show
bindsym $mod+Shift+q exec swaymsg exit
bindsym $mod+Shift+r reload
bindsym $mod+g gaps inner all toggle 25, gaps outer all toggle 10
bindsym $mod+q kill
bindsym $mod+r exec wmenu-run
bindsym $mod+t split toggle
bindsym $mod+x exec swaylock
bindsym Pause exec swaylock
bindsym Print exec grim
bindsym XF86AudioLowerVolume exec wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindsym XF86AudioMicMute exec wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindsym XF86AudioMute exec wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindsym XF86AudioRaiseVolume exec wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bindsym XF86MonBrightnessDown exec brightnessctl set 5%-
bindsym XF86MonBrightnessUp exec brightnessctl set 5%+

floating_modifier $mod normal

bar {
    position top
    swaybar_command waybar
}

include /etc/sway/config.d/*
