# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "nvme"
    "uas"
    "sd_mod"
    "sdhci_pci"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-dc2a8ff5-1e6e-47a4-b352-c08c1f95320b";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-dc2a8ff5-1e6e-47a4-b352-c08c1f95320b".device =
    "/dev/disk/by-uuid/dc2a8ff5-1e6e-47a4-b352-c08c1f95320b";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/55C7-1D1A";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/mapper/luks-a4725842-ece5-467d-9598-6583ed21c7eb"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
