# -*- Mode: ruby -*-

Vagrant.configure("2") do |config|

  config.vm.network :forwarded_port, guest: 80, host: 8000
  config.vm.network :private_network, ip: "192.168.50.4"

  config.vm.synced_folder "../code", "/home/vagrant/code"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
  end
end
