# -*- Mode: ruby -*-

HDIR = "../code"
GDIR = "/home/vagrant/code"

Vagrant.configure("2") do |config|
  #config.vm.network :forwarded_port, guest: 8000, host: 8000

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
  end

  config.vm.define "ubuntu" do |m|
    m.vm.box = "ubuntu"
    m.vm.box_url = "http://files.vagrantup.com/precise64.box"

    m.vm.synced_folder HDIR, GDIR
  end

  config.vm.define "arch" do |m|
    m.vm.box = "arch"
  end

  config.vm.define "freebsd" do |m|
    m.vm.box = "freebsd"
    m.vm.guest = :freebsd

    m.vm.synced_folder HDIR, GDIR, :nfs => true

    config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--ioapic", "on"]
      vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
      vb.customize ["modifyvm", :id, "--usb", "off"]
      vb.customize ["modifyvm", :id, "--usbehci", "off"]
      vb.customize ["modifyvm", :id, "--audio", "none"]
      vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
      vb.customize ["modifyvm", :id, "--nictype2", "virtio"]
    end
  end

  config.vm.define "openbsd" do |m|
    m.vm.box = "openbsd-5.3"
    m.vm.guest = :openbsd_v2

    m.vm.synced_folder HDIR, GDIR, :nfs => true, :nfs_version => 4
  end
end
